# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=100, unique=True)),
                ('remote_text', models.TextField(blank=True, null=True)),
                ('remote_date_created', models.DateTimeField(blank=True, null=True)),
                ('remote_date_modified', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11, null=True, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ('-remote_date_created',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openrov.Location')),
            ],
            options={
                'verbose_name': 'videos',
                'ordering': ('video_id',),
            },
        ),
    ]
