# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openrov', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-date_created',), 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('video_id',), 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='remote_date_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='remote_date_modified',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='remote_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='location',
            name='remote_id',
        ),
    ]
