# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openrov', '0002_auto_20170728_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
