# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrov', '0003_auto_20170729_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='text',
        ),
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
